# Generated by Django 6.0 on 2025-12-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesdemo',
            name='content',
            field=models.CharField(max_length=150),
        ),
    ]
